credentialsName: "testing.json"

availability_spreadsheet: Availability

spreadsheet: Server Dashboard

worksheets:
  - Jedi 2
  - Jedi 3
  - Jedi 4
  - Jedi 5
  - Jedi 6
  - Jedi 7
  - Jedi 8
  - Jedi 9
  - Jedi 12
  - Jedi 13
  - Vader 1
  - Vader 2
  - Vader 3
  - Vader 4
